# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20180118_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_api', models.ForeignKey(max_length=225, on_delete=django.db.models.deletion.CASCADE, related_name='user_api', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(max_length=225, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='apiuser')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_via_api',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by_api',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
